version: "3.8"

services:
  status:
    image: ghcr.io/solavvgs-ikt/status-display:latest
    container_name: status-display
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ALLOWED_STATUSES: "Tilgjengelig,Møte,Ute på oppdrag"
      AUTH_TOKEN: ""
    volumes:
      - ./data:/app/data
      - ./static/content:/app/static/content
